### ISSUE TITLE
Tracker - Main Tracker Table Titles

### ISSUE THREAD

**Issue by festarr** [lucylee-412/lost-ark-tracker#1]
As a user of the Lost Ark Tracker web app, I would like to see my weekly progress of every relevant piece of content in the game for each of my characters.

- [x] Create a table with 18 columns.
  - [ ] Center table, add 2px border and radius property to round out the corners
  - *Number of rows will be dynamic and addressed in a different story
- [x] Each column title left to right should be "Character", "iLvl", "📝", "🩸", "🧊", "🌱", "👼🏼", "☣️", "👿", "🐱", "☠️", "Guardian", "Abyssal", "Valtan", "Vykas", "Kakul", "Brel", "Kayangel", "Akkan"
  - [x] Center text/icons horizontally and vertically
  - [ ] Use Roboto font with h3 level heading
  - [ ] Cell background color should be #9fc5e8
