### ISSUE TITLE
Tracker - Main Tracker Table Content

### ISSUE THREAD

**Issue by festarr** [lucylee-412/lost-ark-tracker#2]
As a user of the Lost Ark Tracker web app, I would like to interact with the tracker table to keep track of my weekly progress
 
- [ ] Background color of content should be white
- [ ] Content of column for "Character", and "iLvl" should be editable
  -  [ ] "Character" column should only allow alpha characters
  - [ ] "iLvl" column should only numeric characters
    - [ ] Limit amount of numbers to the thousands and allow only 2 decimals (XXXX.XX)
- [ ] Content of every other column should be a checkbox
  - [ ] When user checks a checkbox, the corresponding cell should change to color #fff2cc
- [ ] Content of Legion Raids should have an additional button underneath the checkbox
  - [ ] Button should be labeled "Skip"
  - [ ] When user clicks the Skip button, the checkbox should become disabled
